{% set version = "2.0.1" %}

package:
  name: bob.io.audio
  version: {{ version }}

source:
  fn: bob.io.audio-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.io.audio/bob.io.audio-{{ version }}.zip
  md5: 5c025adb4b48c2f4b4f4a5c0f6d70b0e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - scipy
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
  - bob.io.matlab
  - boost 1.61.*
  - sox
  - pkg-config

  run:
  - python
  - scipy
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
  - bob.io.matlab
  - boost 1.61.*
  - sox

test:
  imports:
  - bob
  - bob.io
  - bob.io.audio

  commands:
  - nosetests -sv bob.io.audio

  requires:
  - nose

about:
  home: http://github.com/bioidiap/bob.io.audio
  license: GNU General Public License v3 (GPLv3)
  summary: Audio I/O support for Bob

extra:
  recipe-maintainers:
  - 183amir
